# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       hawaii-system-preferences

# >> macros
# << macros

Summary:    Hawaii system preferences package
Version:    0.2.0.1.20131229.8341fd6
Release:    1
Group:      Applications/System
License:    BSD
Source0:    system-preferences-%{version}.tar.bz2
Source1:    xdgdesktopfile.cpp
Source100:  hawaii-system-preferences.yaml
Patch1:     libqtxdg.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  qtaccountsservice-devel
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Xdg)
BuildRequires:  pkgconfig(dconf)
BuildRequires:  qtconfiguration-devel
BuildRequires:  pkgconfig(polkit-qt-1)
BuildRequires:  cmake
BuildRequires:  bzip2-devel
BuildRequires:  xz-devel
BuildRequires:  qt5-qttools-linguist
#BuildRequires:  kde-libkdeqt5staging-devel
#BuildRequires:  kde-kcoreaddons-devel
#BuildRequires:  kde-kconfig-devel
BuildRequires:  qt5-plugin-imageformat-jpeg
BuildRequires:  qt5-plugin-imageformat-gif
BuildRequires:  qt5-plugin-imageformat-ico
BuildRequires:  qt5-plugin-platform-eglfs
BuildRequires:  qt5-plugin-platform-kms
BuildRequires:  qt5-plugin-platform-minimal
BuildRequires:  qt5-plugin-platform-minimalegl
BuildRequires:  qt5-plugin-platform-linuxfb
BuildRequires:  qt5-plugin-platform-offscreen
BuildRequires:  qt5-plugin-platform-xcb
BuildRequires:  qt5-plugin-bearer-nm
BuildRequires:  qt5-plugin-bearer-connman
BuildRequires:  qt5-plugin-bearer-generic


%description
Provides greenisland system preferences for Hawaii desktop

%package devel
Summary:    Hawaii System Preferences development files
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Provides a framework to develop additional System Preference modules



%prep
%setup -q -n system-preferences
cp %{SOURCE1} 3rdparty/libqtxdg/
%patch1 -p1

# >> setup
# << setup

%build
# >> build pre
# << build pre
%ifnarch %{ix86} x86_64
# HACK!!! Please remove when possible.
# cmake is accelerated but version is too old
mkdir /tmp/bin
cp -a /usr/bin/cmake /usr/share/cmake/Modules /usr/share/cmake/Templates /tmp/bin/
PATH=/tmp/bin:$PATH
/tmp/bin/cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_SKIP_RPATH:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON . -DCMAKE_BUILD_TYPE=RelWithDebInfo
%else
%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo
%endif

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_bindir}/hawaii-system-preferences
%{_libdir}/libHawaiiSystemPreferences.so.*
%{_libdir}/hawaii/plugins/preferences/background.so
%{_libdir}/hawaii/plugins/preferences/desktop.so
%{_libdir}/hawaii/plugins/preferences/keyboard.so
%{_libdir}/hawaii/plugins/preferences/network.so
%{_datadir}/applications/hawaii-system-preferences.desktop
%{_datadir}/applications/hawaii-background-panel.desktop
%{_datadir}/applications/hawaii-desktop-panel.desktop
%{_datadir}/applications/hawaii-keyboard-panel.desktop
%{_datadir}/applications/hawaii-network-panel.desktop
%{_datadir}/hawaii-system-preferences/translations/*.qm
%{_datadir}/hawaii-system-preferences/plugins/background/translations/*.qm
%{_datadir}/hawaii-system-preferences/plugins/desktop/translations/*.qm
%{_datadir}/hawaii-system-preferences/plugins/keyboard/translations/*.qm
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/Hawaii/SystemPreferences/
%{_libdir}/libHawaiiSystemPreferences.so
# >> files devel
# << files devel

